--------------------------------------------------------------------------------
-- STEP 0: DROP TABLES SAFE
--------------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE_ROLE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DIVISION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DIRECTORATE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------------------------------------
-- STEP 1: CREATE DIRECTORATE TABLE
--------------------------------------------------------------------------------
CREATE TABLE DIRECTORATE (
  DIRECTORATE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR2(50) NOT NULL
);

--------------------------------------------------------------------------------
-- STEP 2: CREATE DIVISION TABLE
--------------------------------------------------------------------------------
CREATE TABLE DIVISION (
  DIVISION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR2(50) NOT NULL,
  DIRECTORATE_ID NUMBER REFERENCES DIRECTORATE(DIRECTORATE_ID)
);

--------------------------------------------------------------------------------
-- STEP 3: CREATE EMPLOYEE TABLE (PERSONAL DETAILS ONLY)
--------------------------------------------------------------------------------
CREATE TABLE EMPLOYEE (
    EMP_ID VARCHAR2(10) PRIMARY KEY,
    EMP_NAME VARCHAR2(50),
    ADDRESS VARCHAR2(100),
    PHONE VARCHAR2(20),
    AGE NUMBER,
    GENDER VARCHAR2(10),
    EMAIL VARCHAR2(100),

    -- Directorate and Division for employee's primary/current assignment
    DIRECTORATE VARCHAR2(50),
    DIVISION VARCHAR2(50),
    DIRECTORATE_ID NUMBER,
    DIVISION_ID NUMBER,

    CONSTRAINT FK_EMP_DIR FOREIGN KEY (DIRECTORATE_ID)
        REFERENCES DIRECTORATE(DIRECTORATE_ID),

    CONSTRAINT FK_EMP_DIV FOREIGN KEY (DIVISION_ID)
        REFERENCES DIVISION(DIVISION_ID)
);

--------------------------------------------------------------------------------
-- STEP 4: CREATE EMPLOYEE_ROLE TABLE (WITH DIRECTORATE & DIVISION)
--------------------------------------------------------------------------------
CREATE TABLE EMPLOYEE_ROLE (
    ROLE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMP_ID VARCHAR2(10) NOT NULL,
    ROLE_NAME VARCHAR2(50),
    ROLE_NUMBER VARCHAR2(20),
    FROM_DATE DATE,
    TO_DATE DATE,
    
    -- Each role can have its own directorate and division
    DIRECTORATE_ID NUMBER,
    DIVISION_ID NUMBER,

    CONSTRAINT FK_ROLE_EMP
        FOREIGN KEY (EMP_ID)
        REFERENCES EMPLOYEE(EMP_ID)
        ON DELETE CASCADE,
        
    CONSTRAINT FK_ROLE_DIR
        FOREIGN KEY (DIRECTORATE_ID)
        REFERENCES DIRECTORATE(DIRECTORATE_ID),
        
    CONSTRAINT FK_ROLE_DIV
        FOREIGN KEY (DIVISION_ID)
        REFERENCES DIVISION(DIVISION_ID)
);

--------------------------------------------------------------------------------
-- STEP 5: INSERT DIRECTORATE DATA
--------------------------------------------------------------------------------
INSERT INTO DIRECTORATE (NAME) VALUES ('DIT');
INSERT INTO DIRECTORATE (NAME) VALUES ('DWST');
INSERT INTO DIRECTORATE (NAME) VALUES ('DOVI');
INSERT INTO DIRECTORATE (NAME) VALUES ('HR');
INSERT INTO DIRECTORATE (NAME) VALUES ('FINANCE');
INSERT INTO DIRECTORATE (NAME) VALUES ('SUPPORT');

--------------------------------------------------------------------------------
-- STEP 6: INSERT DIVISION DATA
--------------------------------------------------------------------------------
-- DIT (ID = 1)
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('SDD', 1);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('CNN', 1);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('NETWORK', 1);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('SYSTEMS', 1);

-- DWST (ID = 2)
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('WATER MGT', 2);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('SEWERAGE', 2);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('STORM WATER', 2);

-- DOVI (ID = 3)
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('OPERATIONS', 3);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('FIELD', 3);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('MAINTENANCE', 3);

-- HR (ID = 4)
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('RECRUITMENT', 4);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('PAYROLL', 4);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('WELFARE', 4);

-- FINANCE (ID = 5)
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('BUDGET', 5);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('AUDIT', 5);

-- SUPPORT (ID = 6)
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('IT HELPDESK', 6);
INSERT INTO DIVISION (NAME, DIRECTORATE_ID) VALUES ('PROCUREMENT', 6);

COMMIT;

--------------------------------------------------------------------------------
-- STEP 7: INSERT EMPLOYEE DATA (PERSONAL DETAILS)
--------------------------------------------------------------------------------
INSERT INTO EMPLOYEE (
  EMP_ID, EMP_NAME, ADDRESS, PHONE, AGE, GENDER, EMAIL,
  DIRECTORATE, DIVISION, DIRECTORATE_ID, DIVISION_ID
) VALUES
('100001','RAMESH KUMAR','HYDERABAD','9876543210',35,'Male',
 'ramesh@drdl.gov.in','DIT','SDD',1,1);

INSERT INTO EMPLOYEE VALUES
('100002','SURESH NAIR','SECUNDERABAD','9123456780',42,'Male',
 'suresh@drdl.gov.in','DWST','SEWERAGE',2,6);

INSERT INTO EMPLOYEE VALUES
('100003','ANITA SHARMA','MIYAPUR','9988776655',29,'Female',
 'anita@drdl.gov.in','DIT','NETWORK',1,3);

INSERT INTO EMPLOYEE VALUES
('100004','RAJESH VERMA','KONDAPUR','9876501234',38,'Male',
 'rajesh@drdl.gov.in','DOVI','OPERATIONS',3,8);

INSERT INTO EMPLOYEE VALUES
('100005','POOJA MEHTA','MADHAPUR','9012345678',26,'Female',
 'pooja@drdl.gov.in','DIT','CNN',1,2);

INSERT INTO EMPLOYEE VALUES
('100006','VIKRAM SINGH','HABSIGUDA','9345678901',45,'Male',
 'vikram@drdl.gov.in','DWST','WATER MGT',2,5);

INSERT INTO EMPLOYEE VALUES
('100007','NEHA GUPTA','UPPAL','9567890123',31,'Female',
 'neha@drdl.gov.in','DOVI','FIELD',3,9);

INSERT INTO EMPLOYEE VALUES
('100008','ARJUN REDDY','LB NAGAR','9789012345',34,'Male',
 'arjun@drdl.gov.in','DIT','NETWORK',1,3);

INSERT INTO EMPLOYEE VALUES
('100009','KAVYA IYER','BANJARA HILLS','9890123456',28,'Female',
 'kavya@drdl.gov.in','DWST','SEWERAGE',2,6);

INSERT INTO EMPLOYEE VALUES
('100010','MOHAN DAS','TARNAKA','9001122334',50,'Male',
 'mohan@drdl.gov.in','DOVI','MAINTENANCE',3,10);

COMMIT;

--------------------------------------------------------------------------------
-- STEP 8: INSERT SAMPLE ROLE DATA
--------------------------------------------------------------------------------
-- Employee 100001 - RAMESH KUMAR - Multiple roles
INSERT INTO EMPLOYEE_ROLE (EMP_ID, ROLE_NAME, ROLE_NUMBER, FROM_DATE, TO_DATE, DIRECTORATE_ID, DIVISION_ID)
VALUES ('100001', 'SOFTWARE ENGINEER', '123456', TO_DATE('01-01-2023', 'DD-MM-YYYY'), TO_DATE('31-12-2023', 'DD-MM-YYYY'), 1, 1);

INSERT INTO EMPLOYEE_ROLE (EMP_ID, ROLE_NAME, ROLE_NUMBER, FROM_DATE, TO_DATE, DIRECTORATE_ID, DIVISION_ID)
VALUES ('100001', 'SENIOR ENGINEER', '123457', TO_DATE('01-01-2024', 'DD-MM-YYYY'), NULL, 1, 1);

-- Employee 100002 - SURESH NAIR
INSERT INTO EMPLOYEE_ROLE (EMP_ID, ROLE_NAME, ROLE_NUMBER, FROM_DATE, TO_DATE, DIRECTORATE_ID, DIVISION_ID)
VALUES ('100002', 'WATER ENGINEER', '234567', TO_DATE('01-06-2022', 'DD-MM-YYYY'), NULL, 2, 6);

-- Employee 100003 - ANITA SHARMA
INSERT INTO EMPLOYEE_ROLE (EMP_ID, ROLE_NAME, ROLE_NUMBER, FROM_DATE, TO_DATE, DIRECTORATE_ID, DIVISION_ID)
VALUES ('100003', 'NETWORK ADMIN', '345678', TO_DATE('15-03-2023', 'DD-MM-YYYY'), NULL, 1, 3);

COMMIT;

--------------------------------------------------------------------------------
-- STEP 9: VERIFY
--------------------------------------------------------------------------------
SELECT E.EMP_ID, E.EMP_NAME, E.DIRECTORATE, E.DIVISION
FROM EMPLOYEE E
ORDER BY E.EMP_ID;

SELECT ER.ROLE_ID, ER.EMP_ID, ER.ROLE_NAME, D.NAME AS DIRECTORATE, DIV.NAME AS DIVISION
FROM EMPLOYEE_ROLE ER
LEFT JOIN DIRECTORATE D ON ER.DIRECTORATE_ID = D.DIRECTORATE_ID
LEFT JOIN DIVISION DIV ON ER.DIVISION_ID = DIV.DIVISION_ID
ORDER BY ER.EMP_ID, ER.FROM_DATE DESC;
